include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  errors:
    todo: ignore

linter:
  rules:
    lines_longer_than_80_chars: false
    depend_on_referenced_packages: false
