/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyIcon {
  MyIcon._();

  static const _kFontFam = 'MyIcon';

  static const IconData link = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData folder = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData arrows_cw =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData doc_text =
      const IconData(0xf0f6, fontFamily: _kFontFam);
  static const IconData doc_inv = const IconData(0xf15b, fontFamily: _kFontFam);
  static const IconData doc_text_inv =
      const IconData(0xf15c, fontFamily: _kFontFam);
  static const IconData file_pdf =
      const IconData(0xf1c1, fontFamily: _kFontFam);
  static const IconData file_word =
      const IconData(0xf1c2, fontFamily: _kFontFam);
  static const IconData file_excel =
      const IconData(0xf1c3, fontFamily: _kFontFam);
  static const IconData file_powerpoint =
      const IconData(0xf1c4, fontFamily: _kFontFam);
  static const IconData file_image =
      const IconData(0xf1c5, fontFamily: _kFontFam);
  static const IconData file_archive =
      const IconData(0xf1c6, fontFamily: _kFontFam);
  static const IconData file_audio =
      const IconData(0xf1c7, fontFamily: _kFontFam);
  static const IconData file_video =
      const IconData(0xf1c8, fontFamily: _kFontFam);
  static const IconData file_code =
      const IconData(0xf1c9, fontFamily: _kFontFam);
}
