name: Analysis

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  check:
    name: analysis
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.x'

      # checkout codebase.
      - name: Checkout codebase
        uses: actions/checkout@v3

      # install ssh key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # Add github token
      - name: Add Github Token
        uses: oleksiyrudenko/gha-git-credentials@v2
        with:
          token: '${{ secrets.TAT_CORE_ACCESS_TOKEN }}'
          email: '${{ secrets.EMAIL }}'

      # Get packages.
      - name: Get dependencies
        run: flutter pub get

      # check code is formatted correctly.
      - name: Ensure the Dart code is formatted correctly
        run: dart format --set-exit-if-changed -l 120 .

      # Analyze, check formatting, and run unit tests.
      - run: flutter analyze

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: '**/*.md'
